Analytics opserver UT is failing
RCA - There is an upstream change in python redis package on 30/04/2019
https://pypi.org/project/redis/3.5.0/ This is giving following error -
File "/home/centos/contrail_repo/build/debug/opserver/.venv/lib/python2.7/site-packages/redis/client.py", line 3042, in hset
    raise DataError("'hset' with no key value pairs")
DataError: 'hset' with no key value pairs

Fix - Pin the python redis version and other package version in requirements.txt
to last known working version.

closes-jira-bug: CEM-15237
Change-Id: If7d99097d6fd3257d40b59f83bd1d13a159117f0